routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/welcome', function () {
//     return view('welcome');
// });

Route::get('admin/login', [\App\Http\Controllers\Auth\AdminLoginController::class, 'showLoginForm']);
Route::post('admin/login', [\App\Http\Controllers\Auth\AdminLoginController::class, 'login']);
Route::get('admin/logout', [\App\Http\Controllers\Auth\AdminLoginController::class, 'logout']);

Route::group(['prefix' => 'admin','middleware' => 'assign.guard:admin,admin/login'],function(){
    Route::get('/dashboard', [\App\Http\Controllers\Admin\DashboardController::class, 'index']);
    Route::resource('/blog-category', \App\Http\Controllers\Admin\BlogCategoryController::class)->name('index','blog-category');
    Route::resource('/blog-post', \App\Http\Controllers\Admin\BlogPostController::class)->name('index', 'blog-post');
    Route::resource('/portfolio-project', \App\Http\Controllers\Admin\PortfolioProjectController::class)->name('index', 'portfolio-project');
    Route::get('/setting', [\App\Http\Controllers\Admin\SettingController::class, 'index'])->name('setting');
    Route::put('/setting', [\App\Http\Controllers\Admin\SettingController::class, 'update'])->name('setting.update');
});

resources/views/admin/portfolio/create.blade.php
@extends('admin.layouts.app')

@section('title', 'admin.portfolio.create_portfolio')

@section('content')
  <!-- BEGIN FORM -->
  <section>
    <div class="section-header">
      <ol class="breadcrumb">
        <li class="active">@lang('admin.portfolio.create_portfolio')</li>
      </ol>
    </div>
    <div class="section-body contain-lg">
      <form class="form" method="post" action="{{ route('portfolio-project.store') }}" enctype="multipart/form-data">
      @csrf

      <!-- BEGIN FIELDS -->
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-head">
                <ul class="nav nav-tabs" data-toggle="tabs">
                  @foreach($languages as $key_language => $language)
                    <li class="{{ $loop->first ? 'active' : '' }}"><a
                        href="#lang-{{ $key_language }}">{{ $language }}</a></li>
                  @endforeach
                </ul>
              </div><!--end .card-head -->
              <div class="card-body tab-content">
                @foreach($languages as $key_language => $language)
                  <div class="tab-pane {{ $loop->first ? 'active' : '' }}" id="lang-{{ $key_language }}">

                    <input type="hidden" name="{{ $key_language }}[language]" value="{{ $key_language }}">

                    <div class="form-group floating-label {{ $errors->has($key_language.'.title')? 'has-error' : '' }}">
                      <input type="text" class="form-control" id="{{ $key_language }}-title" name="{{ $key_language }}[title]" value="{{ Request::old($key_language.'.title') }}">
                      <label for="{{ $key_language }}-title">@lang('admin.portfolio.title_column')</label>
                      @if ($errors->has($key_language.'.title'))
                        <span class="text-danger">{{ $errors->first($key_language.'.title') }}</span>
                      @endif
                    </div>

                    <!-- BEGIN CKEDITOR - STANDARD -->
                    <h4>@lang('admin.portfolio.description')</h4>
                    <div class="form-group floating-label {{ $errors->has($key_language.'.description')? 'has-error' : '' }}">
                      <textarea class="form-control control-12-rows ckeditor" name="{{ $key_language }}[description]" placeholder="Enter text ...">{{ Request::old($key_language.'.description') }}</textarea>
                      @if ($errors->has($key_language.'.description'))
                        <span class="text-danger">{{ $errors->first($key_language.'.description') }}</span>
                      @endif
                    </div>
                    <!-- END CKEDITOR - STANDARD -->

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-meta_title" name="{{ $key_language }}[meta_title]" value="{{ Request::old($key_language.'.meta_title') }}">
                      <label for="{{ $key_language }}-meta_title">@lang('admin.portfolio.meta_title')</label>
                    </div>

                    <div class="form-group floating-label">
                      <textarea class="form-control" id="{{ $key_language }}-meta_description" name="{{ $key_language }}[meta_description]">{{ Request::old($key_language.'.meta_description') }}</textarea>
                      <label for="{{ $key_language }}-meta_description">@lang('admin.portfolio.meta_description')</label>
                    </div>

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-slag" name="{{ $key_language }}[slag]" value="{{ Request::old($key_language.'.slag') }}">
                      <label for="{{ $key_language }}-slag">@lang('admin.portfolio.slag')</label>
                    </div>

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-keyword" name="{{ $key_language }}[keyword]" value="{{ Request::old($key_language.'.keyword') }}">
                      <label for="{{ $key_language }}-keyword">@lang('admin.portfolio.keyword')</label>
                    </div>

                  </div>
                @endforeach
              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->
        </div><!--end .row -->

        <!-- BEGIN FILE UPLOAD -->
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-head style-primary">
                <header>Images</header>
              </div>
              <div class="card-body no-padding">
                <div class="form-group col-sm-12 block_images">
                  <div class="col-sm-6">
                    <div class="upload-file-container preview_image">
                      <div class="image col-sm-4 text-center">
                        <div class="image_file"></div>
                        <div class="upload-file-container-text">
                          <span><i class="md md-add-to-photos"></i> Add image</span>
                          <input type="file" name="portfolio_project_image[0][image]" data-key="0" class="image_input"/>
                        </div>
                      </div>
                      <div class="sort col-sm-6">
                        <input type="text" name="portfolio_project_image[0][sort]" placeholder="sort">
                      </div>
                      <div class="delete col-sm-2" style="display: none">
                        <button type="submit" class="btn btn-icon-toggle" data-toggle="tooltip" data-original-title="Delete image"><i class="fa fa-trash-o"></i></button>
                      </div>
                    </div>
                  </div>
                </div>
              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->
        </div><!--end .row -->
        <!-- END FILE UPLOAD -->

        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-body">

                <div class="form-group floating-label">
                  <input type="text" class="form-control" id="sort_order" name="sort_order" value="{{ Request::old('sort_order') }}">
                  <label for="sort_order">@lang('admin.portfolio.sort_order')</label>
                </div>

                <div class="form-group">
                  <label for="sort_order">@lang('admin.portfolio.status')</label>
                  <select class="form-control" data-placeholder="Select an item" id="status" name="status">
                    <option value="1" {{ Request::old('status') == 1 ? 'selected' : '' }}>@lang('admin.enable')</option>
                    <option value="0" {{ Request::old('status') == 0 ? 'selected' : '' }}>@lang('admin.disable')</option>
                  </select>
                </div>

              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->
        </div><!--end .row -->
        <!-- END FIELDS -->

        <button class="btn ink-reaction btn-raised btn-primary">@lang('admin.submit')</button>
      </form>

    </div><!--end .section-body -->
  </section>
  <!-- END FORM -->
@endsection
@push('script')
  <script>
    $('body').delegate('.image_input','change', function () {
      var input = this;
      if (input.files && input.files[0]) {
        var key = parseInt($(input).attr('data-key')) + 1;
        var reader = new FileReader();
        reader.onload = function (e) {
          $(input).parent().parent().parent().find('.delete').removeAttr('style');
          $(input).parent().siblings('.image_file').html('<img src="' + e.target.result + '" alt="image">');
          $(input).parent().removeClass('upload-file-container-text');
          $(input).siblings('span').remove();

          var new_input = '<div class="col-sm-6">' +
            '<div class="upload-file-container preview_image">' +
            '<div class="image col-sm-4 text-center">' +
            '<div class="image_file">' +
            '</div>' +
            '<div class="upload-file-container-text">' +
            '<span><i class="md md-add-to-photos"></i> Add image</span>' +
            '<input type="file" name="portfolio_project_image['+ key +'][image]" data-key="'+ key +'" class="image_input"/>' +
            '</div>' +
            '</div>' +
            '<div class="sort col-sm-6">' +
            '<input type="text" name="portfolio_project_image['+ key +'][sort]" placeholder="sort">' +
            '</div>' +
            '<div class="delete col-sm-2" style="display: none">' +
            '<button type="submit" class="btn btn-icon-toggle" data-toggle="tooltip" data-placement="top" data-original-title="Delete image"><i class="fa fa-trash-o"></i></button>' +
            '</div>' +
            '</div>' +
            '</div>';
          $('.block_images').prepend(new_input);
        };
        reader.readAsDataURL(input.files[0]);
      }
    });

    $('body').delegate('.delete button','click', function (e) {
      e.preventDefault();
      console.log($(this).parent().parent())
      $(this).parent().parent().remove();
    });
  </script>
@endpush

resources/views/admin/portfolio/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'admin.blog.blog_post.create_post')

@section('content')
  <!-- BEGIN FORM -->
  <section>
    <div class="section-header">
      <ol class="breadcrumb">
        <li class="active">@lang('admin.portfolio.create_post')</li>
      </ol>
    </div>
    <div class="section-body contain-lg">
      <form class="form" method="post" enctype="multipart/form-data" action="{{ route('portfolio-project.update', $portfolioProject->id) }}">
      @csrf
      @method('PUT')

      <!-- BEGIN FIELDS -->
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-head">
                <ul class="nav nav-tabs" data-toggle="tabs">
                  @foreach($languages as $key_language => $language)
                    <li class="{{ $loop->first ? 'active' : '' }}"><a
                        href="#lang-{{ $key_language }}">{{ $language }}</a></li>
                  @endforeach
                </ul>
              </div><!--end .card-head -->
              <div class="card-body tab-content">
                @foreach($languages as $key_language => $language)
                  <div class="tab-pane {{ $loop->first ? 'active' : '' }}" id="lang-{{ $key_language }}">

                    <input type="hidden" name="{{ $key_language }}[language]" value="{{ $key_language }}">

                    <div class="form-group floating-label {{ $errors->has($key_language.'.title')? 'has-error' : '' }}">
                      <input type="text" class="form-control" id="{{ $key_language }}-title" name="{{ $key_language }}[title]" value="{{ issetPrint($portfolioProjectDescriptions, $key_language, 'title') }}">
                      <label for="{{ $key_language }}-title">@lang('admin.portfolio.title_column')</label>
                      @if ($errors->has($key_language.'.title'))
                        <span class="text-danger">{{ $errors->first($key_language.'.title') }}</span>
                      @endif
                    </div>

                    <!-- BEGIN CKEDITOR - STANDARD -->
                    <h4>@lang('admin.portfolio.description')</h4>
                    <div class="form-group floating-label {{ $errors->has($key_language.'.description')? 'has-error' : '' }}">
                      <textarea class="form-control control-12-rows ckeditor" name="{{ $key_language }}[description]" placeholder="Enter text ...">{{ issetPrint($portfolioProjectDescriptions, $key_language, 'description') }}</textarea>
                      @if ($errors->has($key_language.'.description'))
                        <span class="text-danger">{{ $errors->first($key_language.'.description') }}</span>
                      @endif
                    </div>
                    <!-- END CKEDITOR - STANDARD -->

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-meta_title" name="{{ $key_language }}[meta_title]" value="{{ issetPrint($portfolioProjectDescriptions, $key_language, 'meta_title') }}">
                      <label for="{{ $key_language }}-meta_title">@lang('admin.portfolio.meta_title')</label>
                    </div>

                    <div class="form-group floating-label">
                      <textarea class="form-control" id="{{ $key_language }}-meta_description" name="{{ $key_language }}[meta_description]">{{ issetPrint($portfolioProjectDescriptions, $key_language, 'meta_description') }}</textarea>
                      <label for="{{ $key_language }}-meta_description">@lang('admin.portfolio.meta_description')</label>
                    </div>

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-slag" name="{{ $key_language }}[slag]" value="{{ issetPrint($portfolioProjectDescriptions, $key_language, 'slag') }}">
                      <label for="{{ $key_language }}-slag">@lang('admin.portfolio.slag')</label>
                    </div>

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-keyword" name="{{ $key_language }}[keyword]" value="{{ issetPrint($portfolioProjectDescriptions, $key_language, 'keyword') }}">
                      <label for="{{ $key_language }}-keyword">@lang('admin.portfolio.keyword')</label>
                    </div>

                  </div>
                @endforeach
              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->
        </div><!--end .row -->

        <!-- BEGIN FILE UPLOAD -->
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-head style-primary">
                <header>Images</header>
              </div>
              <div class="card-body no-padding">
                <div class="form-group col-sm-12 block_images">

                  <div class="col-sm-6">
                    <div class="upload-file-container preview_image">
                      <div class="image col-sm-4 text-center">
                        <div class="image_file"></div>
                        <div class="upload-file-container-text">
                          <span><i class="md md-add-to-photos"></i> Add image</span>
                          <input type="file" name="portfolio_project_image[{{ $key_image }}][image]" data-key="{{ $key_image }}" class="image_input"/>
                        </div>
                      </div>
                      <div class="sort col-sm-6">
                        <input type="text" name="portfolio_project_image[{{ $key_image }}][sort]" placeholder="sort">
                      </div>
                      <div class="delete col-sm-2" style="display: none">
                        <button type="submit" class="btn btn-icon-toggle" data-toggle="tooltip" data-original-title="Delete image"><i class="fa fa-trash-o"></i></button>
                      </div>
                    </div>
                  </div>

                  @foreach($portfolioProjectImages as $key => $image)
                    <div class="col-sm-6">
                      <div class="upload-file-container preview_image">
                        <div class="image col-sm-4">
                          <img src="{{ $image->image }}">
                          <input type="hidden" name="portfolio_project_image[{{ $key }}][image]" value="{{ $image->image }}">
                        </div>
                        <div class="sort col-sm-6">
                          <input type="text" name="portfolio_project_image[{{ $key }}][sort]" placeholder="sort" value="{{ $image->sort_order }}">
                        </div>
                        <div class="delete col-sm-2">
                          <button type="submit" class="btn btn-icon-toggle" data-toggle="tooltip" data-placement="top" data-original-title="Delete row"><i class="fa fa-trash-o"></i></button>
                        </div>
                      </div>
                    </div>
                  @endforeach

                </div>
              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->
        </div><!--end .row -->
        <!-- END FILE UPLOAD -->

        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-body">

                <div class="form-group floating-label">
                  <input type="text" class="form-control" id="sort_order" name="sort_order" value="{{ $portfolioProject->sort_order }}">
                  <label for="sort_order">@lang('admin.portfolio.sort_order')</label>
                </div>

                <div class="form-group">
                  <label for="sort_order">@lang('admin.portfolio.status')</label>
                  <select class="form-control" data-placeholder="Select an item" id="status" name="status">
                    <option value="1" {{ $portfolioProject->status == 1 ? 'selected' : '' }}>@lang('admin.enable')</option>
                    <option value="0" {{ $portfolioProject->status == 0 ? 'selected' : '' }}>@lang('admin.disable')</option>
                  </select>
                </div>

              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->
        </div><!--end .row -->
        <!-- END FIELDS -->

        <button class="btn ink-reaction btn-raised btn-primary">@lang('admin.submit')</button>
      </form>

    </div><!--end .section-body -->
  </section>
  <!-- END FORM -->
@endsection
@push('script')
  <script>
    $('body').delegate('.image_input','change', function () {
      var input = this;
      if (input.files && input.files[0]) {
        var key = parseInt($(input).attr('data-key')) + 1;
        var reader = new FileReader();
        reader.onload = function (e) {
          $(input).parent().parent().parent().find('.delete').removeAttr('style');
          $(input).parent().siblings('.image_file').html('<img src="' + e.target.result + '" alt="image">');
          $(input).parent().removeClass('upload-file-container-text');
          $(input).siblings('span').remove();

          var new_input = '<div class="col-sm-6">' +
            '<div class="upload-file-container preview_image">' +
            '<div class="image col-sm-4 text-center">' +
            '<div class="image_file">' +
            '</div>' +
            '<div class="upload-file-container-text">' +
            '<span><i class="md md-add-to-photos"></i> Add image</span>' +
            '<input type="file" name="portfolio_project_image['+ key +'][image]" data-key="'+ key +'" class="image_input"/>' +
            '</div>' +
            '</div>' +
            '<div class="sort col-sm-6">' +
            '<input type="text" name="portfolio_project_image['+ key +'][sort]" placeholder="sort">' +
            '</div>' +
            '<div class="delete col-sm-2" style="display: none">' +
            '<button type="submit" class="btn btn-icon-toggle" data-toggle="tooltip" data-placement="top" data-original-title="Delete image"><i class="fa fa-trash-o"></i></button>' +
            '</div>' +
            '</div>' +
            '</div>';
          $('.block_images').prepend(new_input);
        };
        reader.readAsDataURL(input.files[0]);
      }
    });

    $('body').delegate('.delete button','click', function (e) {
      e.preventDefault();
      console.log($(this).parent().parent())
      $(this).parent().parent().remove();
    });
  </script>
@endpush

resources/views/admin/portfolio/list.blade.php
@extends('admin.layouts.app')

@section('title', 'admin.portfolio.title')

@section('content')
  <!-- BEGIN TABLE HOVER -->
  <section class="has-actions style-default-bright">
    <div class="section-body_div">
      <br>
      <h2 class="text-primary">@lang('admin.portfolio.title')
      <a href="{{ route('portfolio-project.create') }}" class="btn ink-reaction btn-raised btn-primary pull-right"><i class="md md-add"></i> New item</a>
      </h2>
      <br>
      <table class="table table-hover">
        <thead>
        <tr>
          <th>@lang('admin.portfolio.id')</th>
          <th>@lang('admin.portfolio.image')</th>
          <th>@lang('admin.portfolio.title_column')</th>
          <th>@lang('admin.portfolio.sort_order')</th>
          <th>@lang('admin.portfolio.status')</th>
          <th class="text-right">@lang('admin.portfolio.actions')</th>
        </tr>
        </thead>
        <tbody>
        @foreach($portfolioProjects as $portfolioProject)
        <tr>
          <td>{{ $portfolioProject->id }}</td>
          <td><img src="{{ isset($portfolioProject->portfolioImage->first()->image) ? $portfolioProject->portfolioImage->first()->image : 'placeholder.png' }}" alt="image" width="180"></td>
          <td>{{ isset($portfolioProject->portfolioDescription->first()->title)?$portfolioProject->portfolioDescription->first()->title:'' }}</td>
          <td>{{ $portfolioProject->sort_order }}</td>
          <td>{{ $portfolioProject->status }}</td>
          <td class="text-right">
            <div class="pull-right">
              <form method="POST" action="{{ route('portfolio-project.destroy', $portfolioProject->id) }}">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-icon-toggle" data-toggle="tooltip" data-placement="top" data-original-title="Delete row"><i class="fa fa-trash-o"></i></button>
              </form>
            </div>
            <a class="btn btn-icon-toggle pull-right" data-toggle="tooltip" data-placement="top" data-original-title="Edit row" href="{{ route('portfolio-project.edit', $portfolioProject->id) }}"><i class="fa fa-pencil"></i></a>
          </td>
        </tr>
        @endforeach
        </tbody>
      </table>
    </div><!--end .section-body -->
  </section>
  <!-- END TABLE HOVER -->
@endsection