routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/welcome', function () {
//     return view('welcome');
// });

Route::get('admin/login', [\App\Http\Controllers\Auth\AdminLoginController::class, 'showLoginForm']);
Route::post('admin/login', [\App\Http\Controllers\Auth\AdminLoginController::class, 'login']);
Route::get('admin/logout', [\App\Http\Controllers\Auth\AdminLoginController::class, 'logout']);

Route::group(['prefix' => 'admin','middleware' => 'assign.guard:admin,admin/login'],function(){
    Route::get('/dashboard', [\App\Http\Controllers\Admin\DashboardController::class, 'index']);
    Route::resource('/blog-category', \App\Http\Controllers\Admin\BlogCategoryController::class)->name('index','blog-category');
    Route::resource('/blog-post', \App\Http\Controllers\Admin\BlogPostController::class)->name('index', 'blog-post');
    Route::resource('/portfolio-project', \App\Http\Controllers\Admin\PortfolioProjectController::class)->name('index', 'portfolio-project');
    Route::get('/setting', [\App\Http\Controllers\Admin\SettingController::class, 'index'])->name('setting');
    Route::put('/setting', [\App\Http\Controllers\Admin\SettingController::class, 'update'])->name('setting.update');
});

app/Models/BlogPost.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class BlogPost extends Model
{
    use HasFactory;

    protected $table = 'blog_post';

    protected $fillable = [
        'category_id',
        'sort_order',
        'status',
        'image'
    ];

    /**
     * @return HasMany
     */
    public function postDescription(): HasMany
    {
        return $this->hasMany(BlogPostDescription::class);
    }

    /**
     * @return HasOne
     */
    public function postDescriptionFirst(): HasOne
    {
        return $this->hasOne(BlogPostDescription::class);
    }

}

app/Http/Controllers/Admin/BlogPostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\BlogCategoryDescription;
use App\Models\BlogPost;
use App\Models\BlogPostDescription;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Validation\Rule;

class BlogPostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $languages = config('app.locales');

        $blogPosts = BlogPost::with(['postDescription'=> function ($q){
            $q->where('language', App::getLocale());
        }])->paginate(25);

        return view('admin.blog.blog_post.list', compact('blogPosts', 'languages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $blogCategories = BlogCategoryDescription::where('language', App::getLocale())->select('title', 'blog_category_id')->get();

        $languages = config('app.locales');

        return view('admin.blog.blog_post.create', compact('languages', 'blogCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $languages = config('app.locales');

        $rules = array();

        foreach ($languages as $keyLanguage => $language){
            $rules[$keyLanguage.'.title'] = 'required';
            $rules[$keyLanguage.'.description'] = 'required';
            $rules[$keyLanguage.'.slag'] = 'unique:blog_category_description,slag';
        }
        $request->validate($rules);

        $blogPost = BlogPost::create($request->all());

        if($request->hasFile('blog_post_image')){
            $file = $request->file('blog_post_image');
            $fileName = $file->getClientOriginalName();
            $path = public_path() . '/storage/uploads/blog_files/';
            $file->move($path, $fileName);
            $blogPost->image = '/storage/uploads/blog_files/' . $fileName;
            $blogPost->save();
        }

        foreach ($languages as $keyLanguage => $language) {
            $blogPostDescription[] = new BlogPostDescription($request->$keyLanguage);
        }

        if(!empty($blogPostDescription)) {
            $blogPost->postDescription()->saveMany($blogPostDescription);
        }

        $request->session()->flash('status', 'BlogPost successful!');

        return redirect()->route('blog-post');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\BlogPost  $blogPost
     * @return \Illuminate\Http\Response
     */
    public function show(BlogPost $blogPost)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\BlogPost  $blogPost
     * @return \Illuminate\Http\Response
     */
    public function edit(BlogPost $blogPost)
    {
        $blogCategories = BlogCategoryDescription::where('language', App::getLocale())->select('title', 'blog_category_id')->get();

        $blogPostDescriptions = $blogPost->postDescription()->get()->keyBy('language');

        $languages = config('app.locales');

        return view('admin.blog.blog_post.edit', compact('blogPost', 'blogPostDescriptions', 'languages', 'blogCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\BlogPost  $blogPost
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, BlogPost $blogPost)
    {
        $languages = config('app.locales');

        $rules = array();

        foreach ($languages as $keyLanguage => $language){
            $description = $blogPost->postDescription()->where(['language' => $keyLanguage])->first();

            $rules[$keyLanguage.'.title'] = 'required';
            $rules[$keyLanguage.'.description'] = 'required';
            $rules[$keyLanguage.'.slag'] = Rule::unique('blog_post_description', 'slag')->ignore(isset($description->id)?$description->id:0);
        }

        $request->validate($rules);

        if($request->hasFile('blog_post_image')){
            $file = $request->file('blog_post_image');
            $fileName = $file->getClientOriginalName();
            $path = public_path() . '/storage/uploads/blog_files/';
            $file->move($path, $fileName);
            $blogPost->image = '/storage/uploads/blog_files/' . $fileName;
        }
        $blogPost->update($request->all());

        $blogPost->postDescription()->delete();

        foreach ($languages as $keyLanguage => $language) {
            $blogPostDescription[] = new BlogPostDescription($request->$keyLanguage);
        }

        if(!empty($blogPostDescription)) {
            $blogPost->postDescription()->saveMany($blogPostDescription);
        }

        $request->session()->flash('status', 'BlogPost successful!');

        return redirect()->route('blog-post');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\BlogPost  $blogPost
     * @return \Illuminate\Http\Response
     */
    public function destroy(BlogPost $blogPost)
    {
        $blogPost->postDescription()->delete();

        $blogPost->delete();

        request()->session()->flash('status', 'BlogPost successful!');

        return redirect()->route('blog-post');
    }
}

app/Http/Controllers/BlogPostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\BlogCategoryDescription;
use App\Models\BlogPost;
use App\Models\BlogPostDescription;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Validation\Rule;

class BlogPostController extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function getPosts(Request $request): \Illuminate\Http\JsonResponse
    {
        $blogPosts = BlogPost::with(['postDescriptionFirst' => function ($q) use ($request){
            $q->where('language', $request->lang);
        }])->where('status', 1);

        if(isset($request->category_id)){
            $blogPosts = $blogPosts->where('category_id', $request->category_id);
        }

        $blogPosts = $blogPosts->limit($request->limit)->get();

        return response()->json($blogPosts);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function getPost(Request $request): \Illuminate\Http\JsonResponse
    {
        $blogPost = BlogPost::with(['postDescriptionFirst' => function ($q) use ($request){
            $q->where('language', $request->lang);
        }])->where(['id' => $request->id, 'status' => 1])->first();

        return response()->json($blogPost);
    }
}

resources/views/admin/blog/blog_post/create.blade.php
@extends('admin.layouts.app')

@section('title', 'admin.blog.blog_post.create_post')

@section('content')
  <!-- BEGIN FORM -->
  <section>
    <div class="section-header">
      <ol class="breadcrumb">
        <li class="active">@lang('admin.blog.blog_post.create_post')</li>
      </ol>
    </div>
    <div class="section-body contain-lg">
      <form class="form" method="post" enctype="multipart/form-data" action="{{ route('blog-post.store') }}">
      @csrf

      <!-- BEGIN FIELDS -->
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-head">
                <ul class="nav nav-tabs" data-toggle="tabs">
                  @foreach($languages as $key_language => $language)
                    <li class="{{ $loop->first ? 'active' : '' }}"><a
                        href="#lang-{{ $key_language }}">{{ $language }}</a></li>
                  @endforeach
                </ul>
              </div><!--end .card-head -->
              <div class="card-body tab-content">
                @foreach($languages as $key_language => $language)
                  <div class="tab-pane {{ $loop->first ? 'active' : '' }}" id="lang-{{ $key_language }}">

                    <input type="hidden" name="{{ $key_language }}[language]" value="{{ $key_language }}">

                    <div class="form-group floating-label {{ $errors->has($key_language.'.title')? 'has-error' : '' }}">
                      <input type="text" class="form-control" id="{{ $key_language }}-title" name="{{ $key_language }}[title]" value="{{ Request::old($key_language.'.title') }}">
                      <label for="{{ $key_language }}-title">@lang('admin.blog.blog_post.title')</label>
                      @if ($errors->has($key_language.'.title'))
                        <span class="text-danger">{{ $errors->first($key_language.'.title') }}</span>
                      @endif
                    </div>

                    <!-- BEGIN CKEDITOR - STANDARD -->
                    <h4>@lang('admin.blog.blog_post.description')</h4>
                    <div class="form-group floating-label {{ $errors->has($key_language.'.description')? 'has-error' : '' }}">
                      <textarea class="form-control control-12-rows ckeditor" name="{{ $key_language }}[description]" placeholder="Enter text ...">{{ Request::old($key_language.'.description') }}</textarea>
                      @if ($errors->has($key_language.'.description'))
                        <span class="text-danger">{{ $errors->first($key_language.'.description') }}</span>
                      @endif
                    </div>
                    <!-- END CKEDITOR - STANDARD -->

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-meta_title" name="{{ $key_language }}[meta_title]" value="{{ Request::old($key_language.'.meta_title') }}">
                      <label for="{{ $key_language }}-meta_title">@lang('admin.blog.blog_post.meta_title')</label>
                    </div>

                    <div class="form-group floating-label">
                      <textarea class="form-control" id="{{ $key_language }}-meta_description" name="{{ $key_language }}[meta_description]">{{ Request::old($key_language.'.meta_description') }}</textarea>
                      <label for="{{ $key_language }}-meta_description">@lang('admin.blog.blog_post.meta_description')</label>
                    </div>

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-slag" name="{{ $key_language }}[slag]" value="{{ Request::old($key_language.'.slag') }}">
                      <label for="{{ $key_language }}-slag">@lang('admin.blog.blog_post.slag')</label>
                    </div>

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-keyword" name="{{ $key_language }}[keyword]" value="{{ Request::old($key_language.'.keyword') }}">
                      <label for="{{ $key_language }}-keyword">@lang('admin.blog.blog_post.keyword')</label>
                    </div>

                  </div>
                @endforeach
              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->
        </div><!--end .row -->

        <div class="row">
          <div class="col-md-6">
            <div class="card">
              <div class="card-body">

                <div class="form-group">
                  <label for="category_id">@lang('admin.blog.blog_post.category_id')</label>
                  <select class="form-control select2-list" data-placeholder="Select an item" id="category_id" name="category_id">
                    <option value="0"> </option>
                    @foreach($blogCategories as $category)
                      <option value="{{ $category->blog_category_id }}" {{ Request::old('category_id') == $category->blog_category_id ? 'selected' : '' }}>{{ $category->title }}</option>
                    @endforeach
                  </select>
                </div>

                <div class="form-group floating-label">
                  <input type="text" class="form-control" id="sort_order" name="sort_order" value="{{ Request::old('sort_order') }}">
                  <label for="sort_order">@lang('admin.blog.blog_post.sort_order')</label>
                </div>

                <div class="form-group">
                  <label for="sort_order">@lang('admin.blog.blog_post.status')</label>
                  <select class="form-control" data-placeholder="Select an item" id="status" name="status">
                    <option value="1" {{ Request::old('status') == 1 ? 'selected' : '' }}>@lang('admin.enable')</option>
                    <option value="0" {{ Request::old('status') == 0 ? 'selected' : '' }}>@lang('admin.disable')</option>
                  </select>
                </div>

              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->

          <div class="col-md-6">
            <div class="card block-blog_post_image">
              <div class="card-head style-primary">
                <header>Image</header>
              </div>
              <div class="card-body no-padding">
                <div class="form-group col-sm-12 block_images">

                  <div class="col-sm-12">
                    <div class="upload-file-container preview_image">
                      <div class="image col-sm-7 text-center">
                        <div class="image_file"></div>
                        <div class="upload-file-container-text block-add-image">
                          <span><i class="md md-add-to-photos"></i> Add image</span>
                          <input type="file" name="blog_post_image" class="image_input"/>
                        </div>
                      </div>
                      <div class="delete col-sm-25">
                        <button type="submit" class="btn btn-icon-toggle" data-toggle="tooltip" data-original-title="Delete image"><i class="fa fa-trash-o"></i></button>
                      </div>
                    </div>
                  </div>
                </div>
              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->

        </div><!--end .row -->
        <!-- END FIELDS -->

        <button class="btn ink-reaction btn-raised btn-primary">@lang('admin.submit')</button>
      </form>

    </div><!--end .section-body -->
  </section>
  <!-- END FORM -->
@endsection
@push('script')
  <script>
    $('body').delegate('.image_input','change', function () {
      var input = this;
      if (input.files && input.files[0]) {
        var key = parseInt($(input).attr('data-key')) + 1;
        var reader = new FileReader();
        reader.onload = function (e) {
          $(input).parent().siblings('.image_file').html('<img src="' + e.target.result + '" alt="image">');
          $(input).siblings('span').css('display', 'none');
          $(input).parent().removeClass('upload-file-container-text');
        };
        reader.readAsDataURL(input.files[0]);
      }
    });

    $('body').delegate('.delete button','click', function (e) {
      e.preventDefault();
      console.log($(this).parent().parent().find('.image_input'))
      $(this).parent().parent().find('.image_input').val('');
      $(this).parent().parent().find('.image_file img').remove();
      $(this).parent().parent().find('.block-add-image').addClass('upload-file-container-text');
      $(this).parent().parent().find('.block-add-image span').css('display', 'block');
    });
  </script>
@endpush

resources/views/admin/blog/blog_post/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'admin.blog.blog_post.create_post')

@section('content')
  <!-- BEGIN FORM -->
  <section>
    <div class="section-header">
      <ol class="breadcrumb">
        <li class="active">@lang('admin.blog.blog_post.create_post')</li>
      </ol>
    </div>
    <div class="section-body contain-lg">
      <form class="form" method="post" enctype="multipart/form-data" action="{{ route('blog-post.update', $blogPost->id) }}">
      @csrf
      @method('PUT')

      <!-- BEGIN FIELDS -->
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-head">
                <ul class="nav nav-tabs" data-toggle="tabs">
                  @foreach($languages as $key_language => $language)
                    <li class="{{ $loop->first ? 'active' : '' }}"><a
                        href="#lang-{{ $key_language }}">{{ $language }}</a></li>
                  @endforeach
                </ul>
              </div><!--end .card-head -->
              <div class="card-body tab-content">
                @foreach($languages as $key_language => $language)
                  <div class="tab-pane {{ $loop->first ? 'active' : '' }}" id="lang-{{ $key_language }}">

                    <input type="hidden" name="{{ $key_language }}[language]" value="{{ $key_language }}">

                    <div class="form-group floating-label {{ $errors->has($key_language.'.title')? 'has-error' : '' }}">
                      <input type="text" class="form-control" id="{{ $key_language }}-title" name="{{ $key_language }}[title]" value="{{ issetPrint($blogPostDescriptions, $key_language, 'title') }}">
                      <label for="{{ $key_language }}-title">@lang('admin.blog.blog_post.title')</label>
                      @if ($errors->has($key_language.'.title'))
                        <span class="text-danger">{{ $errors->first($key_language.'.title') }}</span>
                      @endif
                    </div>

                    <!-- BEGIN CKEDITOR - STANDARD -->
                    <h4>@lang('admin.blog.blog_post.description')</h4>
                    <div class="form-group floating-label {{ $errors->has($key_language.'.description')? 'has-error' : '' }}">
                      <textarea class="form-control control-12-rows ckeditor" name="{{ $key_language }}[description]" placeholder="Enter text ...">{{ issetPrint($blogPostDescriptions, $key_language, 'description') }}</textarea>
                      @if ($errors->has($key_language.'.description'))
                        <span class="text-danger">{{ $errors->first($key_language.'.description') }}</span>
                      @endif
                    </div>
                    <!-- END CKEDITOR - STANDARD -->

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-meta_title" name="{{ $key_language }}[meta_title]" value="{{ issetPrint($blogPostDescriptions, $key_language, 'meta_title') }}">
                      <label for="{{ $key_language }}-meta_title">@lang('admin.blog.blog_post.meta_title')</label>
                    </div>

                    <div class="form-group floating-label">
                      <textarea class="form-control" id="{{ $key_language }}-meta_description" name="{{ $key_language }}[meta_description]">{{ issetPrint($blogPostDescriptions, $key_language, 'meta_description') }}</textarea>
                      <label for="{{ $key_language }}-meta_description">@lang('admin.blog.blog_post.meta_description')</label>
                    </div>

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-slag" name="{{ $key_language }}[slag]" value="{{ issetPrint($blogPostDescriptions, $key_language, 'slag') }}">
                      <label for="{{ $key_language }}-slag">@lang('admin.blog.blog_post.slag')</label>
                    </div>

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-keyword" name="{{ $key_language }}[keyword]" value="{{ issetPrint($blogPostDescriptions, $key_language, 'keyword') }}">
                      <label for="{{ $key_language }}-keyword">@lang('admin.blog.blog_post.keyword')</label>
                    </div>

                  </div>
                @endforeach
              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->
        </div><!--end .row -->


        <div class="row">
          <div class="col-md-6">
            <div class="card">
              <div class="card-body">

                <div class="form-group">
                  <label for="category_id">@lang('admin.blog.blog_post.category_id')</label>
                  <select class="form-control select2-list" data-placeholder="Select an item" id="category_id" name="category_id">
                    <option value="0"> </option>
                    @foreach($blogCategories as $category)
                      <option value="{{ $category->blog_category_id }}" {{ $blogPost->category_id == $category->blog_category_id ? 'selected' : '' }}>{{ $category->title }}</option>
                    @endforeach
                  </select>
                </div>

                <div class="form-group floating-label">
                  <input type="text" class="form-control" id="sort_order" name="sort_order" value="{{ $blogPost->sort_order }}">
                  <label for="sort_order">@lang('admin.blog.blog_post.sort_order')</label>
                </div>

                <div class="form-group">
                  <label for="sort_order">@lang('admin.blog.blog_post.status')</label>
                  <select class="form-control" data-placeholder="Select an item" id="status" name="status">
                    <option value="1" {{ $blogPost->status == 1 ? 'selected' : '' }}>@lang('admin.enable')</option>
                    <option value="0" {{ $blogPost->status == 0 ? 'selected' : '' }}>@lang('admin.disable')</option>
                  </select>
                </div>

              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->

          <div class="col-md-6">
            <div class="card block-blog_post_image">
              <div class="card-head style-primary">
                <header>Image</header>
              </div>
              <div class="card-body no-padding">
                <div class="form-group col-sm-12 block_images">

                  <div class="col-sm-12">
                    <div class="upload-file-container preview_image">
                      <div class="image col-sm-7 text-center">
                        <div class="image_file">
                          @if($blogPost->image)
                            <img alt="image_post" src="{{ $blogPost->image }}" alt="image" width="250">
                          @endif
                        </div>
                        <div class="{{!$blogPost->image?'upload-file-container-text':''}} block-add-image">
                          <span {{$blogPost->image?'style=display:none':''}}><i class="md md-add-to-photos"></i> Add image</span>
                          <input type="file" name="blog_post_image" class="image_input"/>
                        </div>
                      </div>
                      <div class="delete col-sm-25">
                        <button type="submit" class="btn btn-icon-toggle" data-toggle="tooltip" data-original-title="Delete image"><i class="fa fa-trash-o"></i></button>
                      </div>
                    </div>
                  </div>
                </div>
              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->
        </div><!--end .row -->
        <!-- END FIELDS -->

        <button class="btn ink-reaction btn-raised btn-primary">@lang('admin.submit')</button>
      </form>

    </div><!--end .section-body -->
  </section>
  <!-- END FORM -->
@endsection
@push('script')
  <script>
    $('body').delegate('.image_input','change', function () {
      var input = this;
      if (input.files && input.files[0]) {
        var key = parseInt($(input).attr('data-key')) + 1;
        var reader = new FileReader();
        reader.onload = function (e) {
          $(input).parent().siblings('.image_file').html('<img src="' + e.target.result + '" alt="image">');
          $(input).siblings('span').css('display', 'none');
          $(input).parent().removeClass('upload-file-container-text');
        };
        reader.readAsDataURL(input.files[0]);
      }
    });

    $('body').delegate('.delete button','click', function (e) {
      e.preventDefault();
      console.log($(this).parent().parent().find('.image_input'))
      $(this).parent().parent().find('.image_input').val('');
      $(this).parent().parent().find('.image_file img').remove();
      $(this).parent().parent().find('.block-add-image').addClass('upload-file-container-text');
      $(this).parent().parent().find('.block-add-image span').css('display', 'block');
    });
  </script>
@endpush

resources/views/admin/blog/blog_post/list.blade.php
@extends('admin.layouts.app')

@section('title', 'admin.blog.blog_post.title')

@section('content')
  <!-- BEGIN TABLE HOVER -->
  <section class="has-actions style-default-bright">
    <div class="section-body_div">
      <br>
      <h2 class="text-primary">@lang('admin.blog.blog_post.title')
      <a href="{{ route('blog-post.create') }}" class="btn ink-reaction btn-raised btn-primary pull-right"><i class="md md-add"></i> New item</a>
      </h2>
      <br>
      <table class="table table-hover">
        <thead>
        <tr>
          <th>@lang('admin.blog.blog_post.id')</th>
          <th>@lang('admin.blog.blog_post.image')</th>
          <th>@lang('admin.blog.blog_post.title')</th>
          <th>@lang('admin.blog.blog_post.sort_order')</th>
          <th>@lang('admin.blog.blog_post.status')</th>
          <th class="text-right">@lang('admin.blog.blog_post.actions')</th>
        </tr>
        </thead>
        <tbody>
        @foreach($blogPosts as $blogPost)
        <tr>
          <td>{{ $blogPost->id }}</td>
          <td><img src="{{ $blogPost->image ? $blogPost->image : 'placeholder.png' }}" alt="image" width="180"></td>
          <td>{{ isset($blogPost->postDescription->first()->title)?$blogPost->postDescription->first()->title:'' }}</td>
          <td>{{ $blogPost->sort_order }}</td>
          <td>{{ $blogPost->status }}</td>
          <td class="text-right">
            <div class="pull-right">
              <form method="POST" action="{{ route('blog-post.destroy', $blogPost->id) }}">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-icon-toggle" data-toggle="tooltip" data-placement="top" data-original-title="Delete row"><i class="fa fa-trash-o"></i></button>
              </form>
            </div>
            <a class="btn btn-icon-toggle pull-right" data-toggle="tooltip" data-placement="top" data-original-title="Edit row" href="{{ route('blog-post.edit', $blogPost->id) }}"><i class="fa fa-pencil"></i></a>
          </td>
        </tr>
        @endforeach
        </tbody>
      </table>
    </div><!--end .section-body -->
  </section>
  <!-- END TABLE HOVER -->
@endsection