routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/welcome', function () {
//     return view('welcome');
// });

Route::get('admin/login', [\App\Http\Controllers\Auth\AdminLoginController::class, 'showLoginForm']);
Route::post('admin/login', [\App\Http\Controllers\Auth\AdminLoginController::class, 'login']);
Route::get('admin/logout', [\App\Http\Controllers\Auth\AdminLoginController::class, 'logout']);

Route::group(['prefix' => 'admin','middleware' => 'assign.guard:admin,admin/login'],function(){
    Route::get('/dashboard', [\App\Http\Controllers\Admin\DashboardController::class, 'index']);
    Route::resource('/blog-category', \App\Http\Controllers\Admin\BlogCategoryController::class)->name('index','blog-category');
    Route::resource('/blog-post', \App\Http\Controllers\Admin\BlogPostController::class)->name('index', 'blog-post');
    Route::resource('/portfolio-project', \App\Http\Controllers\Admin\PortfolioProjectController::class)->name('index', 'portfolio-project');
    Route::get('/setting', [\App\Http\Controllers\Admin\SettingController::class, 'index'])->name('setting');
    Route::put('/setting', [\App\Http\Controllers\Admin\SettingController::class, 'update'])->name('setting.update');
});

app/Models/BlogCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class BlogCategory extends Model
{
    use HasFactory;

    protected $table = 'blog_category';

    protected $fillable = [
        'parent_id',
        'sort_order',
        'status'
    ];

    /**
     * @return HasMany
     */
    public function categoryDescription(): HasMany
    {
        return $this->hasMany(BlogCategoryDescription::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function categoryDescriptionFirst(): HasOne
    {
        return $this->hasOne(BlogCategoryDescription::class);
    }
}

app/Http/Controllers/Admin/BlogCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\BlogCategory;
use App\Models\BlogCategoryDescription;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Validation\Rule;
use phpDocumentor\Reflection\Location;

class BlogCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $languages = config('app.locales');

        $blogCategories = BlogCategory::with(['categoryDescription'=> function ($q){
            $q->where('language', App::getLocale());
        }])->paginate(25);

        return view('admin.blog.blog_category.list', compact('blogCategories', 'languages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        $blogCategories = BlogCategoryDescription::where('language', App::getLocale())->select('title', 'blog_category_id')->get();

        $languages = config('app.locales');

        return view('admin.blog.blog_category.create', compact('languages', 'blogCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $languages = config('app.locales');

        $rules = array();

        foreach ($languages as $keyLanguage => $language){
            $rules[$keyLanguage.'.title'] = 'required';
            $rules[$keyLanguage.'.description'] = 'required';
            $rules[$keyLanguage.'.slag'] = 'unique:blog_category_description,slag';
        }
        $request->validate($rules);

        $blogCategory = BlogCategory::create($request->all());

        foreach ($languages as $keyLanguage => $language) {
            $blogCategoryDescription[] = new BlogCategoryDescription($request->$keyLanguage);
        }

        if(!empty($blogCategoryDescription)) {
            $blogCategory->categoryDescription()->saveMany($blogCategoryDescription);
        }

        $request->session()->flash('status', 'BlogCategory successful!');

        return redirect()->route('blog-category');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\BlogCategory  $blogCategory
     * @return \Illuminate\Http\Response
     */
    public function show(BlogCategory $blogCategory)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\BlogCategory  $blogCategory
     * @return \Illuminate\Http\Response
     */
    public function edit(BlogCategory $blogCategory)
    {
        $blogCategories = BlogCategoryDescription::where('language', App::getLocale())->select('title', 'blog_category_id')->get();

        $blogCategoryDescriptions = $blogCategory->categoryDescription()->get()->keyBy('language');

        $languages = config('app.locales');

        return view('admin.blog.blog_category.edit', compact('blogCategory', 'blogCategoryDescriptions', 'languages', 'blogCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\BlogCategory $blogCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, BlogCategory $blogCategory)
    {
        $languages = config('app.locales');

        $rules = array();

        foreach ($languages as $keyLanguage => $language){
            $description = $blogCategory->categoryDescription()->where(['language' => $keyLanguage])->first();

            $rules[$keyLanguage.'.title'] = 'required';
            $rules[$keyLanguage.'.description'] = 'required';
            $rules[$keyLanguage.'.slag'] = Rule::unique('blog_category_description', 'slag')->ignore($description->id);
        }

        $request->validate($rules);

        $blogCategory->update($request->all());

        $blogCategory->categoryDescription()->delete();

        foreach ($languages as $keyLanguage => $language) {
            $blogCategoryDescription[] = new BlogCategoryDescription($request->$keyLanguage);
        }

        if(!empty($blogCategoryDescription)) {
            $blogCategory->categoryDescription()->saveMany($blogCategoryDescription);
        }

        $request->session()->flash('status', 'BlogCategory successful!');

        return redirect()->route('blog-category');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\BlogCategory  $blogCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy(BlogCategory $blogCategory)
    {
        $blogCategory->categoryDescription()->delete();

        $blogCategory->delete();

        request()->session()->flash('status', 'BlogCategory successful!');

        return redirect()->route('blog-category');
    }
}

app/Http/Controllers/BlogCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\BlogCategory;
use App\Models\BlogCategoryDescription;
use App\Models\BlogPost;
use App\Models\BlogPostDescription;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Validation\Rule;

class BlogCategoryController extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function getCategories(Request $request): \Illuminate\Http\JsonResponse
    {
        $blogCategories = BlogCategory::with(['categoryDescriptionFirst' => function ($q) use ($request){
            $q->where('language', $request->lang);
        }])->where('status', 1)->limit($request->limit)->get();

        return response()->json($blogCategories);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function getCategory(Request $request): \Illuminate\Http\JsonResponse
    {
        $blogCategory = BlogCategory::with(['categoryDescriptionFirst' => function ($q) use ($request){
            $q->where('language', $request->lang);
        }])->where(['id' => $request->id, 'status' => 1])->first();

        return response()->json($blogCategory);
    }
}

resources/views/admin/blog/blog_category/create.blade.php
@extends('admin.layouts.app')

@section('title', 'admin.blog.blog_category.create_category')

@section('content')
  <!-- BEGIN FORM -->
  <section>
    <div class="section-header">
      <ol class="breadcrumb">
        <li class="active">@lang('admin.blog.blog_category.create_category')</li>
      </ol>
    </div>
    <div class="section-body contain-lg">
      <form class="form" method="post" action="{{ route('blog-category.store') }}">
      @csrf

      <!-- BEGIN FIELDS -->
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-head">
                <ul class="nav nav-tabs" data-toggle="tabs">
                  @foreach($languages as $key_language => $language)
                    <li class="{{ $loop->first ? 'active' : '' }}"><a
                        href="#lang-{{ $key_language }}">{{ $language }}</a></li>
                  @endforeach
                </ul>
              </div><!--end .card-head -->
              <div class="card-body tab-content">
                @foreach($languages as $key_language => $language)
                  <div class="tab-pane {{ $loop->first ? 'active' : '' }}" id="lang-{{ $key_language }}">

                    <input type="hidden" name="{{ $key_language }}[language]" value="{{ $key_language }}">

                    <div class="form-group floating-label {{ $errors->has($key_language.'.title')? 'has-error' : '' }}">
                      <input type="text" class="form-control" id="{{ $key_language }}-title" name="{{ $key_language }}[title]" value="{{ Request::old($key_language.'.title') }}">
                      <label for="{{ $key_language }}-title">@lang('admin.blog.blog_category.title')</label>
                      @if ($errors->has($key_language.'.title'))
                        <span class="text-danger">{{ $errors->first($key_language.'.title') }}</span>
                      @endif
                    </div>

                    <!-- BEGIN CKEDITOR - STANDARD -->
                    <h4>@lang('admin.blog.blog_category.description')</h4>
                    <div class="form-group floating-label {{ $errors->has($key_language.'.description')? 'has-error' : '' }}">
                      <textarea class="form-control control-12-rows ckeditor" name="{{ $key_language }}[description]" placeholder="Enter text ...">{{ Request::old($key_language.'.description') }}</textarea>
                      @if ($errors->has($key_language.'.description'))
                        <span class="text-danger">{{ $errors->first($key_language.'.description') }}</span>
                      @endif
                    </div>
                    <!-- END CKEDITOR - STANDARD -->

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-meta_title" name="{{ $key_language }}[meta_title]" value="{{ Request::old($key_language.'.meta_title') }}">
                      <label for="{{ $key_language }}-meta_title">@lang('admin.blog.blog_category.meta_title')</label>
                    </div>

                    <div class="form-group floating-label">
                      <textarea class="form-control" id="{{ $key_language }}-meta_description" name="{{ $key_language }}[meta_description]">{{ Request::old($key_language.'.meta_description') }}</textarea>
                      <label for="{{ $key_language }}-meta_description">@lang('admin.blog.blog_category.meta_description')</label>
                    </div>

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-slag" name="{{ $key_language }}[slag]" value="{{ Request::old($key_language.'.slag') }}">
                      <label for="{{ $key_language }}-slag">@lang('admin.blog.blog_category.slag')</label>
                    </div>

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-keyword" name="{{ $key_language }}[keyword]" value="{{ Request::old($key_language.'.keyword') }}">
                      <label for="{{ $key_language }}-keyword">@lang('admin.blog.blog_category.keyword')</label>
                    </div>

                  </div>
                @endforeach
              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->
        </div><!--end .row -->

        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-body">

                <div class="form-group">
                  <label for="sort_order">@lang('admin.blog.blog_category.parent_id')</label>
                  <select class="form-control select2-list" data-placeholder="Select an item" id="parent_id" name="parent_id">
                    <option value="0"> </option>
                    @foreach($blogCategories as $category)
                      <option value="{{ $category->blog_category_id }}" {{ Request::old('parent_id') == $category->blog_category_id ? 'selected' : '' }}>{{ $category->title }}</option>
                    @endforeach
                  </select>
                </div>

                <div class="form-group floating-label">
                  <input type="text" class="form-control" id="sort_order" name="sort_order" value="{{ Request::old('sort_order') }}">
                  <label for="sort_order">@lang('admin.blog.blog_category.sort_order')</label>
                </div>

                <div class="form-group">
                  <label for="sort_order">@lang('admin.blog.blog_category.status')</label>
                  <select class="form-control" data-placeholder="Select an item" id="status" name="status">
                    <option value="1" {{ Request::old('status') == 1 ? 'selected' : '' }}>@lang('admin.enable')</option>
                    <option value="0" {{ Request::old('status') == 0 ? 'selected' : '' }}>@lang('admin.disable')</option>
                  </select>
                </div>

              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->
        </div><!--end .row -->
        <!-- END FIELDS -->

        <button class="btn ink-reaction btn-raised btn-primary">@lang('admin.submit')</button>
      </form>

    </div><!--end .section-body -->
  </section>
  <!-- END FORM -->
@endsection

resources/views/admin/blog/blog_category/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'admin.blog.blog_category.edit_category')

@section('content')
  <!-- BEGIN FORM -->
  <section>
    <div class="section-header">
      <ol class="breadcrumb">
        <li class="active">@lang('admin.blog.blog_category.edit_category')</li>
      </ol>
    </div>
    <div class="section-body contain-lg">
      <form class="form" method="post" action="{{ route('blog-category.update', $blogCategory->id) }}">
      @csrf
      @method('PUT')

      <!-- BEGIN FIELDS -->
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-head">
                <ul class="nav nav-tabs" data-toggle="tabs">
                  @foreach($languages as $key_language => $language)
                    <li class="{{ $loop->first ? 'active' : '' }}"><a href="#lang-{{ $key_language }}">{{ $language }}</a></li>
                  @endforeach
                </ul>
              </div><!--end .card-head -->
              <div class="card-body tab-content">
                @foreach($languages as $key_language => $language)
                  <div class="tab-pane {{ $loop->first ? 'active' : '' }}" id="lang-{{ $key_language }}">

                    <input type="hidden" name="{{ $key_language }}[language]" value="{{ $key_language }}">

                    <div class="form-group floating-label {{ $errors->has($key_language.'.title')? 'has-error' : '' }}">
                      <input type="text" class="form-control" id="{{ $key_language }}-title" name="{{ $key_language }}[title]" value="{{ issetPrint($blogCategoryDescriptions, $key_language, 'title') }}">
                      <label for="{{ $key_language }}-title">@lang('admin.blog.blog_category.title')</label>
                      @if ($errors->has($key_language.'.title'))
                        <span class="text-danger">{{ $errors->first($key_language.'.title') }}</span>
                      @endif
                    </div>

                    <!-- BEGIN CKEDITOR - STANDARD -->
                    <h4>@lang('admin.blog.blog_category.description')</h4>
                    <div class="form-group floating-label {{ $errors->has($key_language.'.description')? 'has-error' : '' }}">
                      <textarea class="form-control control-12-rows ckeditor" name="{{ $key_language }}[description]" placeholder="Enter text ...">{{ issetPrint($blogCategoryDescriptions, $key_language, 'description') }}</textarea>
                      @if ($errors->has($key_language.'.description'))
                        <span class="text-danger">{{ $errors->first($key_language.'.description') }}</span>
                      @endif
                    </div>
                    <!-- END CKEDITOR - STANDARD -->

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-meta_title" name="{{ $key_language }}[meta_title]" value="{{ issetPrint($blogCategoryDescriptions, $key_language, 'meta_title') }}">
                      <label for="{{ $key_language }}-meta_title">@lang('admin.blog.blog_category.meta_title')</label>
                    </div>

                    <div class="form-group floating-label">
                      <textarea class="form-control" id="{{ $key_language }}-meta_description" name="{{ $key_language }}[meta_description]" value="{{ issetPrint($blogCategoryDescriptions, $key_language, 'meta_description') }}"></textarea>
                      <label for="{{ $key_language }}-meta_description">@lang('admin.blog.blog_category.meta_description')</label>
                    </div>

                    <div class="form-group floating-label {{ $errors->has($key_language.'.slag')? 'has-error' : '' }}">
                      <input type="text" class="form-control" id="{{ $key_language }}-slag" name="{{ $key_language }}[slag]" value="{{ issetPrint($blogCategoryDescriptions, $key_language, 'slag') }}">
                      <label for="{{ $key_language }}-slag">@lang('admin.blog.blog_category.slag')</label>
                      @if ($errors->has($key_language.'.slag'))
                        <span class="text-danger">{{ $errors->first($key_language.'.slag') }}</span>
                      @endif
                    </div>

                    <div class="form-group floating-label">
                      <input type="text" class="form-control" id="{{ $key_language }}-keyword" name="{{ $key_language }}[keyword]" value="{{ issetPrint($blogCategoryDescriptions, $key_language, 'keyword') }}">
                      <label for="{{ $key_language }}-keyword">@lang('admin.blog.blog_category.keyword')</label>
                    </div>

                  </div>
                @endforeach
              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->
        </div><!--end .row -->


        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-body">

                <div class="form-group">
                  <label for="sort_order">@lang('admin.blog.blog_category.parent_id')</label>
                  <select class="form-control select2-list" data-placeholder="Select an item" id="parent_id" name="parent_id">
                    <option value="0"></option>
                    @foreach($blogCategories as $category)
                      @if($blogCategory->id != $category->blog_category_id)
                        <option value="{{ $category->blog_category_id }}" {{ $blogCategory->parent_id == $category->blog_category_id ? 'selected' : '' }}>{{ $category->title }}</option>
                      @endif
                    @endforeach
                  </select>
                </div>

                <div class="form-group floating-label">
                  <input type="text" class="form-control" id="sort_order" name="sort_order" value="{{ $blogCategory->sort_order }}">
                  <label for="sort_order">@lang('admin.blog.blog_category.sort_order')</label>
                </div>

                <div class="form-group">
                  <label for="sort_order">@lang('admin.blog.blog_category.status')</label>
                  <select class="form-control" data-placeholder="Select an item" id="status" name="status">
                    <option value="1" {{ $blogCategory->status == 1 ? 'selected' : '' }}>@lang('admin.enable')</option>
                    <option value="0" {{ $blogCategory->status == 0 ? 'selected' : '' }}>@lang('admin.disable')</option>
                  </select>
                </div>
              </div><!--end .card-body -->
            </div><!--end .card -->
          </div><!--end .col -->
        </div><!--end .row -->
        <!-- END FIELDS -->

        <button class="btn ink-reaction btn-raised btn-primary">@lang('admin.submit')</button>
      </form>

    </div><!--end .section-body -->
  </section>
  <!-- END FORM -->
@endsection

resources/views/admin/blog/blog_category/list.blade.php
@extends('admin.layouts.app')

@section('title', 'admin.blog.blog_category.title')

@section('content')
  <!-- BEGIN TABLE HOVER -->
  <section class="has-actions style-default-bright">
    <div class="section-body_div">
      <br>
      <h2 class="text-primary">@lang('admin.blog.blog_category.title')
      <a href="{{ route('blog-category.create') }}" class="btn ink-reaction btn-raised btn-primary pull-right"><i class="md md-add"></i> New item</a>
      </h2>
      <br>
      <table class="table table-hover">
        <thead>
        <tr>
          <th>@lang('admin.blog.blog_category.id')</th>
          <th>@lang('admin.blog.blog_category.title')</th>
          <th>@lang('admin.blog.blog_category.sort_order')</th>
          <th>@lang('admin.blog.blog_category.status')</th>
          <th class="text-right">@lang('admin.blog.blog_category.actions')</th>
        </tr>
        </thead>
        <tbody>
        @foreach($blogCategories as $blogCategory)
        <tr>
          <td>{{ $blogCategory->id }}</td>
          <td>{{ isset($blogCategory->categoryDescription->first()->title)?$blogCategory->categoryDescription->first()->title:'' }}</td>
          <td>{{ $blogCategory->sort_order }}</td>
          <td>{{ $blogCategory->status }}</td>
          <td class="text-right">
            <div class="pull-right">
              <form method="POST" action="{{ route('blog-category.destroy', $blogCategory->id) }}">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-icon-toggle" data-toggle="tooltip" data-placement="top" data-original-title="Delete row"><i class="fa fa-trash-o"></i></button>
              </form>
            </div>
            <a class="btn btn-icon-toggle pull-right" data-toggle="tooltip" data-placement="top" data-original-title="Edit row" href="{{ route('blog-category.edit', $blogCategory->id) }}"><i class="fa fa-pencil"></i></a>
          </td>
        </tr>
        @endforeach
        </tbody>
      </table>
    </div><!--end .section-body -->
  </section>
  <!-- END TABLE HOVER -->
@endsection